#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export MAIl=asenat@student.42.fr
export VISUAL=vim
export EDITOR=vim
export TERM=xterm-256color
export CPPUNIT_PATH=$HOME/tools/cppunit
