#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export MAIL="asenat@student.42.fr"
export VISUAL="nvim"
export EDITOR="nvim"
export TERM="xterm-256color"
export PATH=$HOME/.brew/bin:$HOME/.npm-global/bin:$HOME/.cargo/bin:$PATH
bindkey -M viins "kj" vi-cmd-mode
