set nocompatible
syntax on

" Undo file.
set undofile
set undodir=$HOME/.vim/undodir
set undolevels=1000
set undoreload=10000

" swaps files
set directory=$HOME/.vim/swap/

" visual helpers
set number
set showcmd

" incremental search
set hlsearch
set incsearch
if has('nvim')
  set inccommand=nosplit
endif

" two-space auto-indentation
set autoindent
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab

" OK, wrap lines but don't split words
set wrap
set linebreak

" auto-complete with <Tab> in command mode
set wildmenu
set wildmode=longest,full

inoremap kj <esc>
