call plug#begin()
Plug 'honza/vim-snippets'
Plug 'brooth/far.vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'airblade/vim-gitgutter'
Plug 'terryma/vim-multiple-cursors'
Plug 'rafi/awesome-vim-colorschemes'
Plug 'w0rp/ale'
Plug 'kien/ctrlp.vim'
Plug 'zchee/deoplete-jedi'
Plug 'Shougo/deoplete.nvim'
Plug 'rust-lang/rust.vim'
Plug 'pbondoer/vim-42header'
Plug 'roxma/nvim-yarp'
Plug 'morhetz/gruvbox'
Plug 'roxma/vim-hug-neovim-rpc'
call plug#end()

"Set custom tab width according to language
autocmd FileType c,cpp,asm,s,php,html set ts=4 sw=4

inoremap kj <esc>

" General config.
set nu
set mouse=a
set smarttab
set modeline
set ruler
set history=100
set nowrap
set title
set showmatch
set showcmd
set hlsearch
set incsearch
set ignorecase
set smartcase
set backspace=indent,eol,start
"set cursor collumn and line coloration
let mapleader=";"
set background=dark
colorscheme gruvbox
"colorscheme minimalist

"copy/paste from/to clipboard
" set clipboard=unnamedplus

set wildignore+=*.so,*.a,*.o,*.zip,*.out

" Undo file.
set undofile
set undodir=$HOME/.vim/undodir
set undolevels=1000
set undoreload=10000
" swaps files

set directory=$HOME/.vim/swap/
" Hide coloration of found words

map <C-C> :nohlsearch<CR>

let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'

"airline config
let g:airline_theme='gruvbox'
let g:airline#extensions#tabline#enabled = 2
let g:airline#extensions#tabline#fnamemod = ':t'
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'
let g:airline#extensions#tabline#right_sep = ' '
let g:airline#extensions#tabline#right_alt_sep = '|'
let g:airline_left_sep = ' '
let g:airline_left_alt_sep = '|'
let g:airline_right_sep = ' '
let g:airline_right_alt_sep = '|'

" GitGutter settings
let g:gitgutter_sign_added='┃'
let g:gitgutter_sign_modified='┃'
let g:gitgutter_sign_removed='◢'
let g:gitgutter_sign_removed_first_line='◥'
let g:gitgutter_sign_modified_removed='◢'

"ale settings
"ale c linter settings
let g:ale_c_gcc_options="-Wall -Wextra -Werror"
let g:ale_c_gcc_executable="clang"
let g:ale_lint_on_text_changed = 'never'
" You can disable this option too
" if you don't want linters to run on opening a file
let g:ale_lint_on_enter = 0

"Enable deoplete
let g:deoplete#enable_at_startup = 1

" clang format
map <C-K> :py3f ~/.clang-format/42-format.py<cr>
imap <C-K> <c-o>:py3f ~/.clang-format/42-format.py<cr>

inoremap () ()<left>
inoremap [] []<left>
inoremap "" ""<left>
inoremap '' ''<left>
inoremap {} {}<left>
inoremap <> <><left>
tnoremap kj <C-\><C-n>

