#!/usr/bin/bash

fversion=$(rpm -E %fedora)

rpmfusion_free="https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$fversion.noarch.rpm"
rpmfusion_nonfree="https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$fversion.noarch.rpm"

if [ -z "$1" ]; then
  echo "Usage: $0 [name]" 1>&2
  exit 1
fi

echo "Creating container $1..."
toolbox create -c $1 -i "fedora-toolbox:$fversion"

run="toolbox run -c $1"

echo "Upgrading RPM base..."
$run sudo dnf -y upgrade

echo "Installing RPM default tools..."
$run sudo dnf install -y                    \
  neovim vim                                \
  make bear cmake meson ccache              \
  clang gcc gcc-c++ nasm clang-tools-extra  \
  gdb                                       \
  tig patch file ripgrep                    \
  $rpmfusion_free $rpmfusion_nonfree

echo "Done!"
echo "Run toolbox enter -c $1"
