#!/bin/bash

ICON=/usr/share/icons/Ultimate-Plata-Papirus-Icons/32x32@2x/apps/spotify-client.svg

if pgrep -x "spotifyd" > /dev/null
then
	killall spotifyd
	notify-send -i $ICON "Spotifyd stopped"
else
	spotifyd
	notify-send -i $ICON "Spotifyd started!"
fi
