#!/bin/bash

ICON=/usr/share/icons/Ultimate-Plata-Papirus-Icons/32x32@2x/apps/redshift.svg
if pgrep -x "redshift" > /dev/null
then
	killall redshift
	notify-send -i $ICON "redshift stopped"
else
	redshift&
	notify-send -i $ICON "redshift started!"
fi
